from django.urls import path
from django.contrib.auth.views import LogoutView
from appfranco.views import (add_video_juegos,
add_libros,
add_peliculas,
busqueda_video_juegos,
busqueda_libros,
busqueda_peliculas,
resultados_video_juegos,
resultados_libros,
resultados_peliculas,
leer_video_juegos,
leer_libros,
leer_peliculas,
VideoJuegosUpdate,
LibrosUpdate,
PeliculasUpdate,
VideoJuegosDelete,
LibrosDelete,
PeliculasDelete,
login_request,
register_request,
editar_perfil,
about_me,
admin,
index)

urlpatterns = [
    path('video_juegos/', leer_video_juegos, name='leer_video_juegos'),
    path('libros/', leer_libros, name='leer_libros'),
    path('peliculas/', leer_peliculas, name='leer_peliculas'),
    path('video_juegos/add_video_juegos/', add_video_juegos, name='add_video_juegos'),
    path('libros/add_libros/', add_libros, name='add_libros'),
    path('peliculas/add_peliculas/', add_peliculas, name='add_peliculas'),
    path('video_juegos/busqueda_video_juegos/', busqueda_video_juegos, name='busqueda_video_juegos'),
    path('libros/busqueda_libros/', busqueda_libros, name='busqueda_libros'),
    path('peliculas/busqueda_peliculas/', busqueda_peliculas, name='busqueda_peliculas'),
    path('video_juegos/resultados_video_juegos/', resultados_video_juegos, name='resultados_video_juegos'),
    path('libros/resultados_libros/', resultados_libros, name='resultados_libros'),
    path('peliculas/resultados_peliculas/', resultados_peliculas, name='resultados_peliculas'),
    path('video_juegos/actualizar_video_juegos/<pk>', VideoJuegosUpdate.as_view(), name='actualizar_video_juegos'),
    path('libros/actualizar_libros/<pk>', LibrosUpdate.as_view(), name='actualizar_libros'),
    path('peliculas/actualizar_peliculas/<pk>', PeliculasUpdate.as_view(), name='actualizar_peliculas'),
    path('video_juegos/borrar_video_juegos/<pk>', VideoJuegosDelete.as_view(), name='borrar_video_juegos'),
    path('libros/borrar_libros/<pk>', LibrosDelete.as_view(), name='borrar_libros'),
    path('peliculas/borrar_peliculas/<pk>', PeliculasDelete.as_view(), name='borrar_peliculas'),
    path('login/', login_request, name='login'),
    path('registro/', register_request, name='registro'),
    path('logout/', LogoutView.as_view(template_name = 'index.html'), name='logout'),
    path('editar_perfil/', editar_perfil, name='editar_perfil'),
    path('about_me/', about_me, name='about_me'),
    path('admin/', admin, name='admin'),
    path('', index, name='index')
]